<a href="https://colab.research.google.com/github/sumithrapm3/DataScience-ML/blob/main/Numpy_pandas_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Employee Salary Adjustment
A company stores salaries in a NumPy array.

salaries = np.array([45000, 52000, 61000, 48000, 75000])

Tasks:
1.

*  Increase all salaries by 10%.
* Find the average salary
*   Find the maximum and minimum salary
*  Print salaries greater than 60000.

In [2]:
import numpy as np

salaries = np.array([45000, 52000, 61000, 48000, 75000])

# 1. Increase all salaries by 10%
updated_salaries = salaries * 1.10
print("Updated Salaries:", updated_salaries)

# 2. Average salary
print("Average Salary:", np.mean(updated_salaries))

# 3. Max and Min salary
print("Max Salary:", np.max(updated_salaries))
print("Min Salary:", np.min(updated_salaries))

# 4. Salaries greater than 60000
print("Salaries > 60000:", updated_salaries[updated_salaries > 60000])

Updated Salaries: [49500. 57200. 67100. 52800. 82500.]
Average Salary: 61820.0
Max Salary: 82500.0
Min Salary: 49500.00000000001
Salaries > 60000: [67100. 82500.]

Q2. Sales Data Analysis

Daily sales of a store for 10 days:

sales = np.array([120,150,180,200,170,160,210,220,190,175])

Tasks:

* Compute total sales.


* Compute mean and standard deviation.

* Identify days where sales exceeded the average.

* Normalize the sales using Min-Max scaling.

In [3]:
sales = np.array([120,150,180,200,170,160,210,220,190,175])

# 1. Total sales
print("Total Sales:", np.sum(sales))

# 2. Mean and Standard Deviation
print("Mean:", np.mean(sales))
print("Std Dev:", np.std(sales))

# 3. Days where sales exceeded average
avg = np.mean(sales)
print("Above Average Sales:", sales[sales > avg])

# 4. Min-Max Normalization
normalized = (sales - np.min(sales)) / (np.max(sales) - np.min(sales))
print("Normalized Sales:", normalized)

Total Sales: 1775
Mean: 177.5
Std Dev: 28.217902119044926
Above Average Sales: [180 200 210 220 190]
Normalized Sales: [0.   0.3  0.6  0.8  0.5  0.4  0.9  1.   0.7  0.55]

Q3. Matrix Operations for Business Data

A company has sales data for 3 products across 4 regions.

sales_matrix = np.array([

[120,140,130,150],

[80,90,100,95],

[200,210,190,205]
])

Tasks:

1. Find total sales per product.

2. Find total sales per region.
3. Identify the best performing product.
4. Identify the region with highest sales.

In [4]:
sales_matrix = np.array([
    [120,140,130,150],
    [80,90,100,95],
    [200,210,190,205]
])

# 1. Total sales per product
print("Product Sales:", np.sum(sales_matrix, axis=1))

# 2. Total sales per region
print("Region Sales:", np.sum(sales_matrix, axis=0))

# 3. Best performing product
print("Best Product Index:", np.argmax(np.sum(sales_matrix, axis=1)))

# 4. Best region
print("Best Region Index:", np.argmax(np.sum(sales_matrix, axis=0)))

Product Sales: [540 365 805]
Region Sales: [400 440 420 450]
Best Product Index: 2
Best Region Index: 3

Q4. Employee Dataset Exploration

Create a DataFrame:

data = {
'Employee':['A','B','C','D','E','F'],

'Department':['HR','IT','IT','Finance','HR','Finance'],

'Salary':[50000,65000,70000,72000,52000,68000],

'Experience':[2,5,7,6,3,4]
}

Tasks:
1. Convert this dictionary into a DataFrame.
2. Display basic statistics of the dataset.
3. Find the average salary per department.
4. Identify employees with experience greater than 4 years.
5. Add a new column Bonus = 10% of salary.

In [5]:
import pandas as pd

data = {
    'Employee':['A','B','C','D','E','F'],
    'Department':['HR','IT','IT','Finance','HR','Finance'],
    'Salary':[50000,65000,70000,72000,52000,68000],
    'Experience':[2,5,7,6,3,4]
}

df = pd.DataFrame(data)
end="\n"+100*'_'+"\n"
# 1. DataFrame
print("1. DataFrame",end,df)

# 2. Statistics
print("2. Statistics",end,df.describe())

# 3. Average salary per department
print("3. Average salary per department",end,df.groupby('Department')['Salary'].mean())

# 4. Experience > 4
print("4. Experience > 4",end,df[df['Experience'] > 4])

# 5. Bonus column
df['Bonus'] = df['Salary'] * 0.10
print("5.New Column Bonus added",end,df)

1. DataFrame
____________________________________________________________________________________________________
   Employee Department  Salary  Experience
0        A         HR   50000           2
1        B         IT   65000           5
2        C         IT   70000           7
3        D    Finance   72000           6
4        E         HR   52000           3
5        F    Finance   68000           4
2. Statistics
____________________________________________________________________________________________________
              Salary  Experience
count      6.000000    6.000000
mean   62833.333333    4.500000
std     9474.527253    1.870829
min    50000.000000    2.000000
25%    55250.000000    3.250000
50%    66500.000000    4.500000
75%    69500.000000    5.750000
max    72000.000000    7.000000
3. Average salary per department
____________________________________________________________________________________________________
 Department
Finance    70000.0
HR         51000.0
IT         67500.0
Name: Salary, dtype: float64
4. Experience > 4
____________________________________________________________________________________________________
   Employee Department  Salary  Experience
1        B         IT   65000           5
2        C         IT   70000           7
3        D    Finance   72000           6
5.New Column Bonus added
____________________________________________________________________________________________________
   Employee Department  Salary  Experience   Bonus
0        A         HR   50000           2  5000.0
1        B         IT   65000           5  6500.0
2        C         IT   70000           7  7000.0
3        D    Finance   72000           6  7200.0
4        E         HR   52000           3  5200.0
5        F    Finance   68000           4  6800.0

Q5. Missing Data Handling

Dataset:
data = {
'Name':['John','Anna','Peter','Linda','David'],
'Age':[28, np.nan, 35, 32, np.nan],
'Salary':[50000,54000,np.nan,58000,60000]
}

Tasks:
1. Detect missing values.
2. Replace missing Age with mean age.
3. Replace missing Salary with median salary.
4. Remove rows with any remaining missing values.

In [7]:
data = {
    'Name':['John','Anna','Peter','Linda','David'],
    'Age':[28, np.nan, 35, 32, np.nan],
    'Salary':[50000,54000,np.nan,58000,60000]
}

df = pd.DataFrame(data)

# 1. Detect missing values
print("1. Detect missing values",end,df.isnull().sum())

# 2. Fill Age with mean
df['Age'] = df['Age'].fillna(int(df['Age'].mean()))
print("Fill Age with mean",end,df)

# 3. Fill Salary with median
df['Salary'] = df['Salary'].fillna(df['Salary'].median())
print("salary with median",end,df)

# 4. Drop remaining missing
df.dropna(inplace=True)

print("Drop remaining missing values",end,df)

1. Detect missing values
____________________________________________________________________________________________________
 Name      0
Age       2
Salary    1
dtype: int64
Fill Age with mean
____________________________________________________________________________________________________
     Name   Age   Salary
0   John  28.0  50000.0
1   Anna  31.0  54000.0
2  Peter  35.0      NaN
3  Linda  32.0  58000.0
4  David  31.0  60000.0
salary with median
____________________________________________________________________________________________________
     Name   Age   Salary
0   John  28.0  50000.0
1   Anna  31.0  54000.0
2  Peter  35.0  56000.0
3  Linda  32.0  58000.0
4  David  31.0  60000.0
Drop remaining missing values
____________________________________________________________________________________________________
     Name   Age   Salary
0   John  28.0  50000.0
1   Anna  31.0  54000.0
2  Peter  35.0  56000.0
3  Linda  32.0  58000.0
4  David  31.0  60000.0

Q6. Sales Performance Analysis

Dataset:

sales_data = {
'Region':['North','South','East','West','North','South','East','West'],
'Salesperson':['A','B','C','D','E','F','G','H'],
'Sales':[12000,15000,13000,17000,16000,14000,15500,16500]
}

Tasks:
1. Find total sales per region.
2. Identify the top salesperson.
3. Compute average sales across regions.
4. Sort the dataset by sales descending.

Q7. Customer Purchase Analysis

Dataset:

data = {
'CustomerID':[101,102,103,104,105,106,107],
'Age':[25,45,35,50,23,40,60],
'PurchaseAmount':[250,600,400,800,150,700,900],
'City':['Delhi','Mumbai','Delhi','Chennai','Mumbai','Delhi','Chennai']
}

Tasks:
1. Find the average purchase amount by city.
2. Identify customers with purchase above overall average.
3. Find the city generating the highest revenue.
4. Create a column Age_Group:

    o <30 → Young

    o 30–50 → Adult
    
    o 50 → Senior
5. Find average purchase per age group.

In [9]:
data = {
    'CustomerID':[101,102,103,104,105,106,107],
    'Age':[25,45,35,50,23,40,60],
    'PurchaseAmount':[250,600,400,800,150,700,900],
    'City':['Delhi','Mumbai','Delhi','Chennai','Mumbai','Delhi','Chennai']
}

df = pd.DataFrame(data)

# 1. Avg purchase by city
print(df.groupby('City')['PurchaseAmount'].mean())

City
Chennai    850.0
Delhi      450.0
Mumbai     375.0
Name: PurchaseAmount, dtype: float64

In [10]:
# 2. Above average customers
avg = df['PurchaseAmount'].mean()
print(df[df['PurchaseAmount'] > avg])

   CustomerID  Age  PurchaseAmount     City
1         102   45             600   Mumbai
3         104   50             800  Chennai
5         106   40             700    Delhi
6         107   60             900  Chennai

In [11]:
# 3. Highest revenue city
print(df.groupby('City')['PurchaseAmount'].sum().idxmax())

Chennai

In [13]:
# 4. Age group
def age_group(age):
    if age < 30:
        return "Young"
    elif age <= 50:
        return "Adult"
    else:
        return "Senior"

df['Age_Group'] = df['Age'].apply(age_group)
df

   CustomerID  Age  PurchaseAmount     City Age_Group
0         101   25             250    Delhi     Young
1         102   45             600   Mumbai     Adult
2         103   35             400    Delhi     Adult
3         104   50             800  Chennai     Adult
4         105   23             150   Mumbai     Young
5         106   40             700    Delhi     Adult
6         107   60             900  Chennai    Senior

In [14]:

# 5. Avg purchase per age group
print(df.groupby('Age_Group')['PurchaseAmount'].mean())

Age_Group
Adult     625.0
Senior    900.0
Young     200.0
Name: PurchaseAmount, dtype: float64

Q8. Time Series Sales Analysis

Generate data:

dates = pd.date_range('2024-01-01', periods=12, freq='M')

sales = [200,220,250,270,300,320,350,360,380,400,420,450]

df = pd.DataFrame({'Date':dates,'Sales':sales})

Tasks:
1. Convert Date to datetime index.
2. Compute monthly percentage growth.
3. Calculate 3-month rolling average sales.
4. Identify the month with highest growth rate.

In [17]:
dates = pd.date_range('2024-01-01', periods=12, freq='ME')
sales = [200,220,250,270,300,320,350,360,380,400,420,450]

df = pd.DataFrame({'Date':dates,'Sales':sales})

# 1. Set datetime index
df.set_index('Date', inplace=True)
df

            Sales
Date
2024-01-31    200
2024-02-29    220
2024-03-31    250
2024-04-30    270
2024-05-31    300
2024-06-30    320
2024-07-31    350
2024-08-31    360
2024-09-30    380
2024-10-31    400
2024-11-30    420
2024-12-31    450

In [19]:

# 2. Monthly growth
df['Growth'] = df['Sales'].pct_change() * 100
df

            Sales     Growth
Date
2024-01-31    200        NaN
2024-02-29    220  10.000000
2024-03-31    250  13.636364
2024-04-30    270   8.000000
2024-05-31    300  11.111111
2024-06-30    320   6.666667
2024-07-31    350   9.375000
2024-08-31    360   2.857143
2024-09-30    380   5.555556
2024-10-31    400   5.263158
2024-11-30    420   5.000000
2024-12-31    450   7.142857

In [20]:
# 3. Rolling average
df['Rolling_Avg'] = df['Sales'].rolling(window=3).mean()

df

            Sales     Growth  Rolling_Avg
Date
2024-01-31    200        NaN          NaN
2024-02-29    220  10.000000          NaN
2024-03-31    250  13.636364   223.333333
2024-04-30    270   8.000000   246.666667
2024-05-31    300  11.111111   273.333333
2024-06-30    320   6.666667   296.666667
2024-07-31    350   9.375000   323.333333
2024-08-31    360   2.857143   343.333333
2024-09-30    380   5.555556   363.333333
2024-10-31    400   5.263158   380.000000
2024-11-30    420   5.000000   400.000000
2024-12-31    450   7.142857   423.333333

In [22]:
# 4. Highest growth month
print(df['Growth'].idxmax())

2024-03-31 00:00:00